version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: leaderboard-app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /var/www/html
          ignore:
            - vendor/
            - node_modules/
        - action: rebuild
          path: Dockerfile

  db:
    image: postgres:16
    container_name: leaderboard-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: leaderboard-redis
    ports:
      - "6379:6379"

volumes:
  db_data:
